import Provider from "@/redux/Provider";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import SignUpBar from "@/components/SignUpBar";
import NavBar from "@/components/NavBar";
import FooterSection from "@/components/Footer";
import Breadcrumbs from "@/components/BreadCrumbs";
import LogOut from "@/components/LogOut";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700", "300", "500"],
});

const integralcf = localFont({
  src: "./fonts/IntegarCFbold.otf",
  variable: "--font-integral-cf",
  weight: "100 900",
});
const satoshi = localFont({
  src: "./fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi-medium",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} ${integralcf.variable} ${poppins.variable} antialiased`}
      >
        <Provider>
          <SignUpBar />
          <NavBar />
          {/* <div className="absolute top-0 z-50">
            {" "}
            <Breadcrumbs />
          </div> */}
          {children}
          <LogOut />
          <FooterSection />
        </Provider>
      </body>
    </html>
  );
}
